#!/usr/bin/env python3
"""
Run the full data-health audit and persist the snapshot.

Writes:

    data/quality/data_health.json   machine-readable snapshot (served by the API)

and refreshes the generated section of ``docs/data/DATA_HEALTH.md`` between the
``<!-- AUDIT:BEGIN -->`` / ``<!-- AUDIT:END -->`` markers, leaving the
hand-written caveat prose above them untouched.

Run after any backfill, universe change, or panel rebuild — the
``data-inventory-sync`` skill lists this as a mandatory step.

Usage:
    /opt/anaconda3/envs/quant/bin/python scripts/ops/audit_data_health.py
    /opt/anaconda3/envs/quant/bin/python scripts/ops/audit_data_health.py --symbol AAPL
"""

import argparse
import json
import logging
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from core.data.quality.health import load_symbol_detail, run_full_audit

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("audit_data_health")

SNAPSHOT_OUT = ROOT / "data" / "quality" / "data_health.json"
HEALTH_DOC = ROOT / "docs" / "data" / "DATA_HEALTH.md"
BEGIN_MARK = "<!-- AUDIT:BEGIN (generated by scripts/ops/audit_data_health.py — do not edit) -->"
END_MARK = "<!-- AUDIT:END -->"


def render_generated_section(snapshot: dict) -> str:
    """Render the audit snapshot as the markdown block between the doc markers."""
    lines: list[str] = [BEGIN_MARK, "", f"_Last audit: {snapshot['generated_at']}_", ""]

    lines += ["### Universe funnel", "", "| Stage | Count | Note |", "|---|---:|---|"]
    for step in snapshot["funnel"]:
        lines.append(f"| {step['stage']} | {step['count']:,} | {step['note']} |")

    surv = snapshot["survivorship"]
    lines += [
        "",
        "### Survivorship",
        "",
        f"- {surv['with_prices_pct']}% of {surv['delisted_total']:,} delisted names have "
        f"price history; {surv['missing_count']} do not.",
        f"- {surv['price_end_within_30d_of_delisting_pct']}% of covered delisted names have "
        "price history ending within 30 days of their recorded delisting.",
        "- Coverage by delisting era (% with prices):",
        "",
        "| Era | Names | With prices |",
        "|---|---:|---:|",
    ]
    for era in surv["by_delist_era"]:
        lines.append(f"| {era['delist_year']} | {era['names']} | {era['with_prices_pct']}% |")

    pub = snapshot["publication_dates"]
    if "by_decade" in pub:
        lines += [
            "",
            "### Publication-date integrity (statements)",
            "",
            f"- {pub['placeholder_accepted_date_pct']}% of sampled rows had a placeholder "
            f"acceptedDate (remediation: {pub['remediation']}).",
            "",
            "| Decade | Rows | Placeholder |",
            "|---|---:|---:|",
        ]
        for row in pub["by_decade"]:
            lines.append(f"| {row['decade']}s | {row['rows']:,} | {row['placeholder_pct']}% |")

    cal = snapshot["calendar"]
    if cal.get("non_trading_dates") is not None:
        lines += [
            "",
            "### Calendar integrity",
            "",
            f"- Expanded panel: {cal['expanded_dates']:,} dates vs "
            f"{cal['canonical_trading_days']:,} canonical NYSE trading days — "
            f"{cal['non_trading_dates']} non-trading dates "
            f"({cal['weekend_dates']} weekends, {cal['holiday_or_other_dates']} holidays).",
        ]

    lines += [
        "",
        "### Dataset coverage vs universe",
        "",
        "| Dataset | With data | Empty | Missing file |",
        "|---|---:|---:|---:|",
    ]
    for name, stats in snapshot["datasets"].items():
        if "universe_with_data" not in stats:
            lines.append(f"| {name} | — | — | unchecked |")
            continue
        lines.append(
            f"| {name} | {stats['universe_with_data']:,} | {stats['universe_empty_file']:,} "
            f"| {stats['universe_missing_file']:,} |"
        )

    lines += [
        "",
        "### Panel artifacts",
        "",
        "| File | Rows | Symbols | Modified | Size |",
        "|---|---:|---:|---|---:|",
    ]
    for panel in snapshot["panels"]:
        if panel.get("status") == "missing":
            lines.append(f"| {panel['file']} | missing | | | |")
            continue
        lines.append(
            f"| {panel['file']} | {panel['rows']:,} | {panel.get('symbols') or '—'} "
            f"| {panel['modified']} | {panel['size_mb']} MB |"
        )

    intraday = snapshot["intraday"]
    if isinstance(intraday, dict) and "status" not in intraday:
        lines += ["", "### Intraday", ""]
        for interval, stats in intraday.items():
            lines.append(
                f"- **{interval}**: {stats['symbols']} symbols, "
                f"{stats['symbol_year_files']:,} symbol-years "
                f"({stats['empty_symbol_years']} empty), span {stats['year_range']}"
            )

    lines += [
        "",
        "### Known flaws (machine-readable registry)",
        "",
        "| Severity | Flaw | Detail |",
        "|---|---|---|",
    ]
    for flaw in snapshot["flaws"]:
        detail = flaw["detail"].replace("|", "\\|")
        lines.append(f"| **{flaw['severity']}** | {flaw['title']} | {detail} |")

    lines += ["", END_MARK]
    return "\n".join(lines)


def refresh_doc(snapshot: dict) -> None:
    """Replace the generated section of DATA_HEALTH.md, preserving the prose."""
    generated = render_generated_section(snapshot)
    if HEALTH_DOC.exists():
        text = HEALTH_DOC.read_text()
        if BEGIN_MARK in text and END_MARK in text:
            head, rest = text.split(BEGIN_MARK, 1)
            _, tail = rest.split(END_MARK, 1)
            HEALTH_DOC.write_text(head + generated + tail)
            logger.info("Refreshed generated section of %s", HEALTH_DOC.name)
            return
    HEALTH_DOC.write_text(generated + "\n")
    logger.info("Wrote %s (no prose section found; markers created)", HEALTH_DOC.name)


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit data health")
    parser.add_argument("--symbol", type=str, default=None, help="Print one symbol's drilldown")
    args = parser.parse_args()

    if args.symbol:
        detail = load_symbol_detail(args.symbol.upper())
        print(json.dumps(detail, indent=2, default=str))
        return

    snapshot = run_full_audit()
    SNAPSHOT_OUT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT_OUT.write_text(json.dumps(snapshot, indent=2, default=str))
    logger.info("Wrote %s", SNAPSHOT_OUT)
    refresh_doc(snapshot)

    for flaw in snapshot["flaws"]:
        logger.info("[%s] %s", flaw["severity"].upper(), flaw["title"])


if __name__ == "__main__":
    main()
